- README.md
According to the OAuth spec
(http://tools.ietf.org/html/rfc6749#section-3.3) scopes should be
separated by spaces and not commas. I couldn't get multiple scopes to
work successfully using commas with Google APIs.
> Separate scopes by spaces in README example

- README.md
lib/ueberauth/strategy/google.ex#6 sets default_scope to email, fixing
README to reflect that.
Resolves: #12
> Correct default scope in README.md

- lib/ueberauth/strategy/google/oauth.ex
Update with up-to-date URLs from
https://developers.google.com/identity/protocols/OAuth2WebServer
> Update authorize_url and token_url

- lib/ueberauth/strategy/google.ex
See discussion in #9. This new endpoint for obtaining user information returns almost the same information as the old endpoint, but does not require turning on the Google+ API. This follows the OpenID Connect directions at https://developers.google.com/identity/protocols/OpenIDConnect#obtaininguserprofileinformation instead of the Google Sign-In directions.
When testing with my Google account, I found a couple of very minor differences in the bodies of the responses from these two endpoints:
1. The current endpoint returns a ```picture``` URL with a ```sz=50``` query string, which links to a small photo. The OpenID endpoint returns the same URL but with no query string, which links to a large version of the same photo.
2. The current endpoint contains ```"kind" => …
```
> Use the OpenID endpoint to get user profile info

- lib/ueberauth/strategy/google.ex
With elixir 1.3.2 there is a warning:
warning: the variable "opts" is unsafe as it has been set inside a case/cond/receive/if/&&/||.
> fix: elixir warns that the variable opts is unsafe

- README.md
- lib/ueberauth/strategy/google.ex
The `hd` parameter lets you only accept logins from a specific domain. If users are signed in with multiple accounts, this skips the "select your account" page, which makes login quicker. Documented [here](https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters).
It's worth noting that users can tamper with the URL, so you still have to check the response.
I went for `hd` as that's what the parameter is called, and it's how the Google documentation refers to it. Using `hosted_domain` would be more descriptive and wouldn't clash with the Elixir [`hd` function](http://elixir-lang.org/docs/stable/elixir/Kernel.html#hd/1), but I figured consistency with the Google documentation was a higher priority.
> Support Google's hd (hosted domain) parameter

- README.md
- lib/ueberauth/strategy/google.ex
For a web application that needs to access a google account when the
user is present (e.g. polling for analytics) the `approval_prompt` and
`access_type` parameters are required. 
[See the docs](https://developers.google.com/youtube/2.0/developers_guide_protocol_oauth2#OAuth2_Server_Side_Web_Applications_Flow) for more details 
This PR adds the ability to add these options to the request. I've slightly refactored how the `opts` are put together.
Let me know what you think and if there's anything I should change.
> Support more parameters for google OAuth access

- lib/ueberauth/strategy/google.ex
Support for the state param during OAuth redirect was accidentally
removed in 360d6049c9d0bd75b7eef916eb425191883c6f8d.
Fixes #26
> Reintroduce support for state param

- lib/ueberauth/strategy/google.ex
Everything works because google always sends "Bearer" token type and it is the default type for oauth2 library. It's probably smarter to manually take it from the response just in case google or oauth2 will introduce changes.
> Take token type from oauth response

- lib/ueberauth/strategy/google.ex
According to Google's documentation this is required to get refresh token.
https://developers.google.com/identity/protocols/OAuth2WebServer
> Support "prompt" param for offline access

- CHANGELOG.md
- lib/ueberauth/strategy/google.ex
This will allow to override access_type for specific auth flow.
> Allow access_type config as parameter

- lib/ueberauth/strategy/google.ex
- lib/ueberauth/strategy/google/oauth.ex
- for example, redeeming the code again would crash because the strategy was using `OAuth2.Client.get_token!`, which attempts to illegially raise an exception using a OAuth response struct
- Google callbacks are issued with GET so if the auth handler rejects and the user refreshes then the app will crash
- in this set of changes the problem is fixed and the function in `Ueberauth.Strategy.Google.OAuth` is renamed
> fixes crash on regular OAuth callback errors

- README.md
This is related to #44 
See https://developers.google.com/identity/protocols/googlescopes for
more information in the "Google Sign-In" section.
> Corrected "email" scope.

- README.md
- lib/ueberauth/strategy/google.ex
`approval_prompt` has been deprecated and no longer works. It has been replaced by the `prompt` option. You can see the list of parameters here:
https://developers.google.com/identity/protocols/OAuth2WebServer#creatingclient
In the future, it may be worth considering an alternate strategy of just passing through all options directly so a code update isn't necessary every time the options change.
Resolves #49 and is the same as #50 except it renames `prompt` to `approval_prompt` because the later is no longer honored by Google's OAuth.
> Replace deprecated approval_prompt with prompt

- lib/ueberauth/strategy/google.ex
- lib/ueberauth/strategy/google/oauth.ex
I don't want to see strange mistakes. 
I want to use ueberauth_google in my API
I have a front-end and back-end (JSON API) part.
I would like to add ueberauth_google to the back-end and use this on the front-end.
Now the current implementation does not allow me to do it.
Below I will give examples of why I can not do this.
The front-end page is on https://d8765e7f.ngrok.io/test
The back-end page will be on https://d8765e7f.ngrok.io/api/v1/auth/google/callback
> d8765e7f.ngrok.io - local example
**My files**:
config
```elixir
config :ueberauth, Ueberauth,
base_path: "/api/v1/auth",
providers: [
github: {Ueberauth.Strategy.Github, []},
google: { Ueberauth.Strategy.Google, [] },
identity: { Ueberauth.Strategy.Identity, [
callback_methods: ["POST"],
uid_field: :username,
nickname_field: …
```
> Fixed redirect_uri from config

- lib/ueberauth/strategy/google.ex
- lib/ueberauth/strategy/google/oauth.ex
- this allows specifying {m, f, a} tuples for things such as Client ID / Client Secret
> Amended oAuth strategy to resolve m/f/a tuples

- README.md
#60 added ability to read config vars via MFA but there was no information about that in the README
> Added information about reading client_id/client_secret from MFA to the README

- lib/ueberauth/strategy/google.ex
Adds support for the optional `login_hint` param as documented...
https://developers.google.com/identity/protocols/OAuth2WebServer
By setting this param you can avoid the user having to pick from a list of multiple accounts and pre-fill the email with a known value.
> Add support for optional login_hint param

- README.md
The previous wording was misleading as it could be interpreted
as a security mechanism which it definitely isn't.
I tried this out so this is what the login looks like:
However, you can simply fill in any email address:
--> validation still required on the app side.
> `hd:` doesn't limit login to a domain but only suggests it

- README.md
- lib/ueberauth/strategy/google.ex
Closes #78
I also took the liberty of clarifying that the `prompt` and `access_type` have to be both present (as mentioned in #49)
I have tested this in my app and seems to work without any issues :>
> Add support for optional include_granted_scopes param

- README.md
Elixir 1.4 (released in 2016) add application inference, so now in almost all situations it is not necessary to add a dependency to `:applications`. And if you set just a single application in `:applications` then you will break your release.
Since ueberauth_google only support Elixir 1.8 and up, we don't need to mention :applications anymore
> Remove :applications instructions from readme

- lib/ueberauth/strategy/google/oauth.ex
- test/strategy/google_test.exs
** (CaseClauseError) no case clause matching: {:error, %OAuth2.Error{reason: :timeout}}
See spec for https://hexdocs.pm/oauth2/OAuth2.Client.html#get_token/4
```
get_token(client, params \\ [], headers \\ [], opts \\ [])View Source
get_token(t(), params(), headers(), Keyword.t()) ::
{:ok, OAuth2.Client.t()}
| {:error, OAuth2.Response.t()}
| {:error, OAuth2.Error.t()}
```
> Fix crash on not handled Oauth2.Error

- lib/ueberauth/strategy/google/oauth.ex
Hello 👋🏼 
This PR is primarily for discussion purposes, with code as a demonstration.
In the current implementation, if someone configures this provider using the global configuration shown in the README, they cannot then provide a different configuration at the call site. This is because the library overrides local / passed-in configuration options with the global config.
In my opinion, the library should prefer local over global [over the defaults]. This way, different call sites can provide their own options while still falling back to the global config. We intend to use this at CodeSandbox to provide logins via multiple Google OAuth clients — one which is a clear default, and others which are specialized and locally configured.
Always open to feedback and discussion. Thanks!
> Prefer Local Over Global Configuration

- .github/workflows/ci.yml
- .github/workflows/release.yml
I opened another PR and its CI is failing with this error:
```
Run erlef/setup-elixir@v1
with:
elixir-version: 1.11
otp-version: 22.3
github-token: ***
install-hex: true
install-rebar: true
version-type: loose
disable_problem_matchers: false
hexpm-mirrors: https://builds.hex.pm/
Error: Requested Erlang/OTP version (22.3) not found in version list (should you be using option 'version-type': 'strict'?)
```
I have seen this error before. It happened in my project unexpectedly. It happened when the tag `ubuntu-latest` upgraded from 20.04 to 22.04, which no longer supports some older Erlang versions according to this table: https://github.com/erlef/setup-beam#compatibility-between-operating-system-and-erlangotp
> Fix "Requested Erlang/OTP version (22.3) not found in version list " on CI

- CHANGELOG.md
- lib/ueberauth/strategy/google/oauth.ex
- test/strategy/google_test.exs
closes https://github.com/ueberauth/ueberauth_google/issues/98
> Handle %OAuth2.Response{status_code: 503} with no error_description in get_access_token

- CHANGELOG.md
- lib/ueberauth/strategy/google/oauth.ex
- mix.exs
- test/strategy/google/oauth_test.exs
Add the possibility to get the client secret from a module in order to rotate the secret at least every 6 months (which is a good practice) without the need to be changing the config or env var and restart the application. Similar to the implementation of ueberauth_apple: https://github.com/ueberauth/ueberauth_apple/blob/main/guides/getting-started.md#generating-the-client-secret
Configuration would look like this:
```elixir
config :ueberauth, Ueberauth.Strategy.Google.OAuth,
client_id: System.get_env("GOOGLE_CLIENT_ID"),
client_secret: {MyApp.Google, :client_secret}
```
and then:
```elixir
defmodule MyApp.Google
@spec client_secret(config :: keyword) :: String.t()
def client_secret(_config \\ []) do
end
end
```
This does not affect to the current implementation, it is backwards …
> Add the option to get the client secret dynamically.

- CHANGELOG.md
- lib/ueberauth/strategy/google.ex
- mix.exs
- test/strategy/google_test.exs
In order to change the locale in the google interface, the param `hl` have to be passed in the authorization url.
List of supported locales: https://serpapi.com/google-languages
Example URL:
```
https://accounts.google.com/o/oauth2/v2/auth?client_id=client_id&hd=example.com&hl=es&redirect_uri=http%3A%2F%2Fwww.example.com%2Fauth%2Fgoogle%2Fcallback&response_type=code&scope=email+openid&state=wsX_H_KivcqRx03y5mgmrCDm
```
What do you think? @yordis
> Add support to hl param in authorization URL
